# Generated by Django 5.1.2 on 2025-01-06 17:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='default_user', max_length=128)),
                ('email', models.EmailField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/profile_pictures/')),
                ('pwd', models.CharField(max_length=128)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('replies', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('activity_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.category')),
                ('Signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signup')),
                ('tags', models.ManyToManyField(blank=True, to='home.tag')),
            ],
            options={
                'ordering': ['-activity_time'],
            },
        ),
    ]
