# Generated by Django 5.0.9 on 2024-10-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
    ]
