# Generated by Django 4.2 on 2024-10-28 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='default_user', max_length=128),
        ),
    ]
