# Generated by Django 4.2 on 2024-11-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_user_communitypost_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='Signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signup'),
        ),
    ]
